# Generated by Django 4.2.16 on 2024-10-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b04", "0003_calendarevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(),
        ),
    ]
