# Generated by Django 4.2.16 on 2024-10-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("b04", "0006_membership_date_joined"),
    ]

    operations = []
