# Generated by Django 4.2.16 on 2024-10-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("b04", "0007_auto_20241020_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="study_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="b04.studygroup",
            ),
        ),
    ]
