# Generated by Django 4.2.16 on 2024-10-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b04', '0010_keyword_document_description_document_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='upload_at',
        ),
    ]
