# Generated by Django 4.2.16 on 2024-11-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b04", "0011_rename_uploaded_at_document_upload_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="location",
            field=models.CharField(default="Main Library", max_length=255),
        ),
    ]
