# Generated by Django 4.2.16 on 2024-11-20 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b04", "0013_chatroom_message"),
        ("b04", "0013_joinrequest"),
    ]

    operations = []
